In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
%matplotlib inline

In [4]:
train_df = pd.read_csv('train.csv')

In [11]:
train_asses = train_df[train_df['type'] == 'Assessment']

In [12]:
train_asses.head()

event_id      game_session                 timestamp  \
2185  3bfd1a65  901acc108f55a5a1  2019-08-06T05:22:01.344Z   
2186  db02c830  901acc108f55a5a1  2019-08-06T05:22:01.400Z   
2187  a1e4395d  901acc108f55a5a1  2019-08-06T05:22:01.403Z   
2188  a52b92d5  901acc108f55a5a1  2019-08-06T05:22:05.242Z   
2189  a1e4395d  901acc108f55a5a1  2019-08-06T05:22:05.244Z   

                                             event_data installation_id  \
2185  {"version":"1.0","event_count":1,"game_time":0...        0006a69f   
2186  {"event_count":2,"game_time":37,"event_code":2...        0006a69f   
2187  {"description":"Pull three mushrooms out of th...        0006a69f   
2188  {"description":"Pull three mushrooms out of th...        0006a69f   
2189  {"description":"To pick a mushroom, pull it ou...        0006a69f   

      event_count  event_code  game_time                         title  \
2185            1        2000          0  Mushroom Sorter (Assessment)   
2186            2        2025         37  Mushroom Sorter (Assessment)   
2187            3        3010         37  Mushroom Sorter (Assessment)   
2188            4        3110       3901  Mushroom Sorter (Assessment)   
2189            5        3010       3901  Mushroom Sorter (Assessment)   

            type        world  
2185  Assessment  TREETOPCITY  
2186  Assessment  TREETOPCITY  
2187  Assessment  TREETOPCITY  
2188  Assessment  TREETOPCITY  
2189  Assessment  TREETOPCITY

In [13]:
train_asses.drop(['event_data', 'timestamp', 'event_code', 'event_id'], axis=1, inplace=True)

/home/harsh/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3940: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [30]:
train_asses.head()

game_session installation_id  event_count  game_time  \
2185  901acc108f55a5a1        0006a69f            1          0   
2186  901acc108f55a5a1        0006a69f            2         37   
2187  901acc108f55a5a1        0006a69f            3         37   
2188  901acc108f55a5a1        0006a69f            4       3901   
2189  901acc108f55a5a1        0006a69f            5       3901   

                             title        type        world  
2185  Mushroom Sorter (Assessment)  Assessment  TREETOPCITY  
2186  Mushroom Sorter (Assessment)  Assessment  TREETOPCITY  
2187  Mushroom Sorter (Assessment)  Assessment  TREETOPCITY  
2188  Mushroom Sorter (Assessment)  Assessment  TREETOPCITY  
2189  Mushroom Sorter (Assessment)  Assessment  TREETOPCITY

In [31]:
train_asses.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 925345 entries, 2185 to 11337825
Data columns (total 7 columns):
game_session       925345 non-null object
installation_id    925345 non-null object
event_count        925345 non-null int64
game_time          925345 non-null int64
title              925345 non-null object
type               925345 non-null object
world              925345 non-null object
dtypes: int64(2), object(5)
memory usage: 56.5+ MB


In [178]:
train_comb = train_asses.groupby('game_session').max()

In [179]:
train_comb.reset_index(inplace=True)

In [180]:
train_comb.head()

game_session installation_id  event_count  game_time  \
0  00097cda27afb726        01bdd720           36      27810   
1  000f68cff32664ef        3f0dca37          201     118447   
2  0014403daadf67aa        29d1aaee           79     719990   
3  0014daa1d3e26eb2        55fdf49f           72      61995   
4  0018a3df8beb755e        b204dbaf            3         79   

                          title        type         world  
0  Mushroom Sorter (Assessment)  Assessment   TREETOPCITY  
1     Chest Sorter (Assessment)  Assessment  CRYSTALCAVES  
2    Bird Measurer (Assessment)  Assessment   TREETOPCITY  
3  Mushroom Sorter (Assessment)  Assessment   TREETOPCITY  
4    Cart Balancer (Assessment)  Assessment  CRYSTALCAVES

In [181]:
train_lb = pd.read_csv('train_labels.csv')

In [90]:
train_lb.drop(['num_correct', 'num_incorrect', 'accuracy'], axis=1, inplace=True)

In [91]:
train_lb.head()

game_session installation_id                         title  \
0  6bdf9623adc94d89        0006a69f  Mushroom Sorter (Assessment)   
1  77b8ee947eb84b4e        0006a69f    Bird Measurer (Assessment)   
2  901acc108f55a5a1        0006a69f  Mushroom Sorter (Assessment)   
3  9501794defd84e4d        0006a69f  Mushroom Sorter (Assessment)   
4  a9ef3ecb3d1acc6a        0006a69f    Bird Measurer (Assessment)   

   accuracy_group  
0               3  
1               0  
2               3  
3               2  
4               3

In [92]:
train_final = pd.merge(train_comb, train_lb, on=['game_session', 'installation_id', 'title'], how='outer')

In [93]:
train_final.dropna(inplace=True)

In [94]:
train_final.drop('type', axis=1, inplace=True)

In [95]:
train_final.head()

game_session installation_id  event_count  game_time  \
0  00097cda27afb726        01bdd720           36      27810   
1  000f68cff32664ef        3f0dca37          201     118447   
2  0014403daadf67aa        29d1aaee           79     719990   
3  0014daa1d3e26eb2        55fdf49f           72      61995   
5  001c49e9e9968dbe        19d4b097           43      39023   

                          title         world  accuracy_group  
0  Mushroom Sorter (Assessment)   TREETOPCITY             3.0  
1     Chest Sorter (Assessment)  CRYSTALCAVES             0.0  
2    Bird Measurer (Assessment)   TREETOPCITY             1.0  
3  Mushroom Sorter (Assessment)   TREETOPCITY             1.0  
5    Bird Measurer (Assessment)   TREETOPCITY             2.0

In [96]:
train_final['total_assesments'] = 1

In [101]:
train_final['accuracy_group'] = train_final['accuracy_group'].apply(lambda x: int(x))

In [102]:
train_final.head()

game_session installation_id  event_count  game_time  \
0  00097cda27afb726        01bdd720           36      27810   
1  000f68cff32664ef        3f0dca37          201     118447   
2  0014403daadf67aa        29d1aaee           79     719990   
3  0014daa1d3e26eb2        55fdf49f           72      61995   
5  001c49e9e9968dbe        19d4b097           43      39023   

                          title         world  accuracy_group  \
0  Mushroom Sorter (Assessment)   TREETOPCITY               3   
1     Chest Sorter (Assessment)  CRYSTALCAVES               0   
2    Bird Measurer (Assessment)   TREETOPCITY               1   
3  Mushroom Sorter (Assessment)   TREETOPCITY               1   
5    Bird Measurer (Assessment)   TREETOPCITY               2   

   total_assesments  
0                 1  
1                 1  
2                 1  
3                 1  
5                 1

In [103]:
from sklearn.preprocessing import LabelEncoder

In [104]:
encoder = LabelEncoder()

In [105]:
train_final['title_label'] = encoder.fit_transform(train_final['title'])

In [106]:
train_final['world_label'] = encoder.fit_transform(train_final['world'])

In [107]:
train_final.drop(['title', 'world'], axis=1, inplace=True)

In [108]:
train_final.set_index('game_session', inplace=True)

In [109]:
train_final.head()

installation_id  event_count  game_time  accuracy_group  \
game_session                                                               
00097cda27afb726        01bdd720           36      27810               3   
000f68cff32664ef        3f0dca37          201     118447               0   
0014403daadf67aa        29d1aaee           79     719990               1   
0014daa1d3e26eb2        55fdf49f           72      61995               1   
001c49e9e9968dbe        19d4b097           43      39023               2   

                  total_assesments  title_label  world_label  
game_session                                                  
00097cda27afb726                 1            4            2  
000f68cff32664ef                 1            3            0  
0014403daadf67aa                 1            0            2  
0014daa1d3e26eb2                 1            4            2  
001c49e9e9968dbe                 1            0            2

In [110]:
train_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17690 entries, 00097cda27afb726 to fff641eaf483ae2b
Data columns (total 7 columns):
installation_id     17690 non-null object
event_count         17690 non-null int64
game_time           17690 non-null int64
accuracy_group      17690 non-null int64
total_assesments    17690 non-null int64
title_label         17690 non-null int64
world_label         17690 non-null int64
dtypes: int64(6), object(1)
memory usage: 1.1+ MB


In [127]:
test_df = pd.read_csv('test.csv')

In [129]:
test_asses = test_df[test_df['type'] == 'Assessment']

In [131]:
test_asses.drop(['timestamp', 'event_data', 'event_id', 'type'], axis=1, inplace=True)

/home/harsh/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3940: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [136]:
test_final = test_asses.groupby('game_session').max()

In [137]:
test_final['total_assesments'] = 1

In [138]:
test_final['title_label'] = encoder.fit_transform(test_final['title'])

In [140]:
test_final['world_label'] = encoder.fit_transform(test_final['world'])

In [141]:
test_final.drop(['title', 'world'], axis=1, inplace=True)

In [142]:
test_final.head()

installation_id  event_count  event_code  game_time  \
game_session                                                           
001a139acd7fce92        285b65c8          130        4110     181512   
003bafadf2259738        56a739ec           74        4110     168622   
006b058c3bba11a2        d95dc7cb           35        4100      33373   
007195dd54b7c251        6cd8f2d8           27        4100      34553   
007b28de31382377        ce08e98b           47        4100      32339   

                  total_assesments  title_label  world_label  
game_session                                                  
001a139acd7fce92                 1            0            2  
003bafadf2259738                 1            0            2  
006b058c3bba11a2                 1            4            2  
007195dd54b7c251                 1            1            0  
007b28de31382377                 1            4            2

# Model Training and Cross Validation

In [111]:
features = train_final.columns.drop(['accuracy_group', 'installation_id', 'total_assesments'])

In [113]:
X = train_final[features]
y = train_final['accuracy_group']

In [114]:
X.head()

event_count  game_time  title_label  world_label
game_session                                                      
00097cda27afb726           36      27810            4            2
000f68cff32664ef          201     118447            3            0
0014403daadf67aa           79     719990            0            2
0014daa1d3e26eb2           72      61995            4            2
001c49e9e9968dbe           43      39023            0            2

In [115]:
from sklearn.model_selection import train_test_split

In [116]:
X_train, X_cv, y_train, y_cv = train_test_split(X, y, test_size=0.33, random_state=42)

In [117]:
from sklearn.ensemble import RandomForestClassifier

In [118]:
rfc = RandomForestClassifier(n_estimators=200)

In [119]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [121]:
rfc_preds = rfc.predict(X_cv)

In [122]:
from sklearn.metrics import classification_report, confusion_matrix

In [123]:
print(classification_report(y_cv, rfc_preds))

              precision    recall  f1-score   support

           0       0.54      0.50      0.52      1419
           1       0.39      0.41      0.40       763
           2       0.25      0.22      0.23       742
           3       0.74      0.78      0.76      2914

   micro avg       0.59      0.59      0.59      5838
   macro avg       0.48      0.48      0.48      5838
weighted avg       0.58      0.59      0.59      5838



In [124]:
print(confusion_matrix(y_cv, rfc_preds))

[[ 707  241  128  343]
 [ 213  314  118  118]
 [ 134  126  164  318]
 [ 261  133  258 2262]]


In [125]:
from sklearn.metrics import cohen_kappa_score

In [126]:
qwk = cohen_kappa_score(y_cv, rfc_preds, weights='quadratic')
print(qwk)

0.5231085037000176


# Test and Submit

In [185]:
rfc.fit(X, y)
rfc_test = rfc.predict(test_final[features])

In [186]:
test_final['accuracy_group'] = rfc_test

In [187]:
test_final.head()

installation_id  event_count  event_code  game_time  \
game_session                                                           
001a139acd7fce92        285b65c8          130        4110     181512   
003bafadf2259738        56a739ec           74        4110     168622   
006b058c3bba11a2        d95dc7cb           35        4100      33373   
007195dd54b7c251        6cd8f2d8           27        4100      34553   
007b28de31382377        ce08e98b           47        4100      32339   

                  total_assesments  title_label  world_label  accuracy_group  
game_session                                                                  
001a139acd7fce92                 1            0            2               1  
003bafadf2259738                 1            0            2               0  
006b058c3bba11a2                 1            4            2               3  
007195dd54b7c251                 1            1            0               3  
007b28de31382377                 1            4            2               3

In [196]:
test_fn = test_final.groupby('installation_id').sum()

In [197]:
test_fn.head()

event_count  event_code  game_time  total_assesments  \
installation_id                                                         
00abaee7                  27        6100      30038                 2   
01242218                 245       22510     251298                 6   
017c5718                   1        2000          0                 1   
01a44906                   1        2000          0                 1   
01bc6cb6                   1        2000          0                 1   

                 title_label  world_label  accuracy_group  
installation_id                                            
00abaee7                   3            1               2  
01242218                  11            5              11  
017c5718                   4            2               0  
01a44906                   4            2               0  
01bc6cb6                   1            0               0

In [198]:
test_fn['accuracy_group'].unique()

array([  2,  11,   0,   3,  13,   1,   6,  10,  27,  12,  20,  43,   7,
        15,  16,  18,   5,   9,  24,   4,   8,  26,  21,  29,  56,  14,
        19,  17, 107,  66,  48,  23,  37,  78,  40,  36,  22,  32,  39,
        30,  25,  33])

In [199]:
def acc_grp(row):
    row['acc'] = row['accuracy_group']/ row['total_assesments']
    if row['acc'] > 2.33: row['accuracy_group'] = 3
    elif row['acc'] > 1.67: row['accuracy_group'] = 2
    elif row['acc'] > 0.0: row['accuracy_group'] = 1
    else: row['accuracy_group'] = 0
    return row

In [200]:
test_fn = test_fn.apply(acc_grp, axis=1)

In [201]:
test_fn.head()

event_count  event_code  game_time  total_assesments  \
installation_id                                                         
00abaee7                27.0      6100.0    30038.0               2.0   
01242218               245.0     22510.0   251298.0               6.0   
017c5718                 1.0      2000.0        0.0               1.0   
01a44906                 1.0      2000.0        0.0               1.0   
01bc6cb6                 1.0      2000.0        0.0               1.0   

                 title_label  world_label  accuracy_group       acc  
installation_id                                                      
00abaee7                 3.0          1.0             1.0  1.000000  
01242218                11.0          5.0             2.0  1.833333  
017c5718                 4.0          2.0             0.0  0.000000  
01a44906                 4.0          2.0             0.0  0.000000  
01bc6cb6                 1.0          0.0             0.0  0.000000

In [206]:
test_fn['accuracy_group'] = test_fn['accuracy_group'].apply(lambda x: int(x))

In [208]:
test_fn['accuracy_group'].unique()

array([1, 2, 0, 3])